---


- hosts: localhost
  roles:
    - alexisfacques.ansible_module_minio_bucket
  tasks:
    - name: 'This should create a bucket'
      minio_bucket:
        s3_url: http://192.168.1.198:9000
        name: test-bucket
        access_key: H0gH7tjPVFj0M2kh
        secret_key: hbMUE6jCFTaSNK1z
        state: present
        policy: read-only

    - name: 'This should delete a bucket'
      minio_bucket:
        s3_url: http://192.168.1.198:9000
        name: test-bucket
        access_key: H0gH7tjPVFj0M2kh
        secret_key: hbMUE6jCFTaSNK1z
        state: absent
